Repository Gamify-IT/overworld-backend, pull requests merged in 2022-07, with the labels that each got.

#6 Configured pom.xml, changed package names, added springdoc
  .github/workflows/sonarqube-build.yml
  .github/workflows/test.yml
  pom.xml
  src/main/java/com/example/overworldbackend/OverworldBackendApplication.java
  src/main/java/com/example/overworldbackend/controller/OverworldController.java
  src/main/java/com/example/overworldbackend/data/Configuration.java
  src/main/java/de/unistuttgart/overworldbackend/OverworldBackendApplication.java
  src/main/java/de/unistuttgart/overworldbackend/controller/MinigameConfigController.java
  src/main/java/de/unistuttgart/overworldbackend/data/Configuration.java
  src/main/java/de/unistuttgart/overworldbackend/repositories/OverworldRepository.java
  src/main/java/de/unistuttgart/overworldbackend/service/ConfigService.java
  src/main/resources/application.properties
  src/main/resources/db.properties
  src/test/java/de/unistuttgart/overworldbackend/OverworldBackendApplicationTests.java
Labels: maintenance

#7 Create paths, create basic swagger documentation
  src/main/java/de/unistuttgart/overworldbackend/controller/DungeonController.java
  src/main/java/de/unistuttgart/overworldbackend/controller/LectureController.java
  src/main/java/de/unistuttgart/overworldbackend/controller/MinigameConfigController.java
  src/main/java/de/unistuttgart/overworldbackend/controller/MinigameTaskController.java
  src/main/java/de/unistuttgart/overworldbackend/controller/WorldController.java
Labels: documentation, feature

#9 fix database tests
  .github/workflows/test.yml
Labels: bug

#10 Implement logic of area stuff
  .github/workflows/sonarqube-build.yml
  .github/workflows/test.yml
  src/main/java/de/unistuttgart/overworldbackend/OverworldBackendApplication.java
  src/main/java/de/unistuttgart/overworldbackend/controller/DungeonController.java
  src/main/java/de/unistuttgart/overworldbackend/controller/LectureController.java
  src/main/java/de/unistuttgart/overworldbackend/controller/MinigameConfigController.java
  src/main/java/de/unistuttgart/overworldbackend/controller/MinigameTaskController.java
  src/main/java/de/unistuttgart/overworldbackend/controller/NPCController.java
  src/main/java/de/unistuttgart/overworldbackend/controller/WorldController.java
  src/main/java/de/unistuttgart/overworldbackend/data/Area.java
  src/main/java/de/unistuttgart/overworldbackend/data/AreaDTO.java
  src/main/java/de/unistuttgart/overworldbackend/data/Configuration.java
  src/main/java/de/unistuttgart/overworldbackend/data/Dungeon.java
  src/main/java/de/unistuttgart/overworldbackend/data/DungeonDTO.java
  src/main/java/de/unistuttgart/overworldbackend/data/Lecture.java
  src/main/java/de/unistuttgart/overworldbackend/data/LectureDTO.java
  src/main/java/de/unistuttgart/overworldbackend/data/LectureInitialData.java
  src/main/java/de/unistuttgart/overworldbackend/data/MinigameTask.java
  src/main/java/de/unistuttgart/overworldbackend/data/MinigameTaskDTO.java
  src/main/java/de/unistuttgart/overworldbackend/data/NPC.java
  src/main/java/de/unistuttgart/overworldbackend/data/NPCDTO.java
  src/main/java/de/unistuttgart/overworldbackend/data/World.java
  src/main/java/de/unistuttgart/overworldbackend/data/WorldDTO.java
  src/main/java/de/unistuttgart/overworldbackend/data/config/DungeonConfig.java
  src/main/java/de/unistuttgart/overworldbackend/data/config/LectureConfig.java
  src/main/java/de/unistuttgart/overworldbackend/data/config/WorldConfig.java
  src/main/java/de/unistuttgart/overworldbackend/data/mapper/DungeonMapper.java
  src/main/java/de/unistuttgart/overworldbackend/data/mapper/LectureMapper.java
  src/main/java/de/unistuttgart/overworldbackend/data/mapper/MinigameTaskMapper.java
  src/main/java/de/unistuttgart/overworldbackend/data/mapper/NPCMapper.java
  src/main/java/de/unistuttgart/overworldbackend/data/mapper/WorldMapper.java
  src/main/java/de/unistuttgart/overworldbackend/repositories/AreaBaseRepository.java
  src/main/java/de/unistuttgart/overworldbackend/repositories/DungeonRepository.java
  src/main/java/de/unistuttgart/overworldbackend/repositories/LectureRepository.java
  src/main/java/de/unistuttgart/overworldbackend/repositories/MinigameTaskRepository.java
  src/main/java/de/unistuttgart/overworldbackend/repositories/NPCRepository.java
  src/main/java/de/unistuttgart/overworldbackend/repositories/OverworldRepository.java
  src/main/java/de/unistuttgart/overworldbackend/repositories/WorldRepository.java
  src/main/java/de/unistuttgart/overworldbackend/service/ConfigService.java
  src/main/java/de/unistuttgart/overworldbackend/service/DungeonService.java
  src/main/java/de/unistuttgart/overworldbackend/service/LectureService.java
  src/main/java/de/unistuttgart/overworldbackend/service/MinigameTaskService.java
  src/main/java/de/unistuttgart/overworldbackend/service/NPCService.java
  src/main/java/de/unistuttgart/overworldbackend/service/WorldService.java
  src/main/resources/config.json
  src/test/java/de/unistuttgart/overworldbackend/DungeonControllerTest.java
  src/test/java/de/unistuttgart/overworldbackend/LectureControllerTest.java
  src/test/java/de/unistuttgart/overworldbackend/MinigameTaskControllerTest.java
  src/test/java/de/unistuttgart/overworldbackend/NPCControllerTest.java
  src/test/java/de/unistuttgart/overworldbackend/OverworldBackendApplicationTests.java
  src/test/java/de/unistuttgart/overworldbackend/WorldControllerTest.java
Labels: feature

#11 fix code smells
  src/main/java/de/unistuttgart/overworldbackend/data/Area.java
  src/main/java/de/unistuttgart/overworldbackend/service/LectureService.java
  src/main/resources/application.properties
  src/test/java/de/unistuttgart/overworldbackend/LectureControllerTest.java
  src/test/java/de/unistuttgart/overworldbackend/MinigameTaskControllerTest.java
Labels: maintenance

#15 fixed code smells and bugs
  src/main/java/de/unistuttgart/overworldbackend/data/AreaLocation.java
  src/main/java/de/unistuttgart/overworldbackend/data/Dungeon.java
  src/main/java/de/unistuttgart/overworldbackend/data/NPC.java
  src/main/java/de/unistuttgart/overworldbackend/data/mapper/AreaLocationMapper.java
  src/main/java/de/unistuttgart/overworldbackend/repositories/DungeonRepository.java
  src/main/java/de/unistuttgart/overworldbackend/service/PlayerNPCStatisticService.java
  src/main/java/de/unistuttgart/overworldbackend/service/PlayerStatisticService.java
  src/main/java/de/unistuttgart/overworldbackend/service/PlayerTaskStatisticService.java
  src/test/java/de/unistuttgart/overworldbackend/MinigameInputControllerTest.java
  src/test/java/de/unistuttgart/overworldbackend/NPCInputControllerTest.java
  src/test/java/de/unistuttgart/overworldbackend/PlayerNPCStatisticControllerTest.java
  src/test/java/de/unistuttgart/overworldbackend/PlayerTaskStatisticControllerTest.java
Labels: bug, maintenance

#17 Change tags
  src/main/java/de/unistuttgart/overworldbackend/controller/MinigameInputController.java
  src/main/java/de/unistuttgart/overworldbackend/controller/NPCInputController.java
  src/main/java/de/unistuttgart/overworldbackend/controller/PlayerNPCStatisticController.java
  src/main/java/de/unistuttgart/overworldbackend/controller/PlayerStatisticController.java
  src/main/java/de/unistuttgart/overworldbackend/controller/PlayerTaskStatisticController.java
Labels: maintenance

#18 Refactor lecture to course
  src/main/java/de/unistuttgart/overworldbackend/controller/CourseController.java
  src/main/java/de/unistuttgart/overworldbackend/controller/DungeonController.java
  src/main/java/de/unistuttgart/overworldbackend/controller/LectureController.java
  src/main/java/de/unistuttgart/overworldbackend/controller/MinigameTaskController.java
  src/main/java/de/unistuttgart/overworldbackend/controller/NPCController.java
  src/main/java/de/unistuttgart/overworldbackend/controller/PlayerNPCStatisticController.java
  src/main/java/de/unistuttgart/overworldbackend/controller/PlayerStatisticController.java
  src/main/java/de/unistuttgart/overworldbackend/controller/PlayerTaskStatisticController.java
  src/main/java/de/unistuttgart/overworldbackend/controller/WorldController.java
  src/main/java/de/unistuttgart/overworldbackend/data/Area.java
  src/main/java/de/unistuttgart/overworldbackend/data/Course.java
  src/main/java/de/unistuttgart/overworldbackend/data/CourseDTO.java
  src/main/java/de/unistuttgart/overworldbackend/data/CourseInitialData.java
  src/main/java/de/unistuttgart/overworldbackend/data/MinigameTask.java
  src/main/java/de/unistuttgart/overworldbackend/data/NPC.java
  src/main/java/de/unistuttgart/overworldbackend/data/PlayerNPCActionLog.java
  src/main/java/de/unistuttgart/overworldbackend/data/PlayerNPCStatistic.java
  src/main/java/de/unistuttgart/overworldbackend/data/PlayerStatistic.java
  src/main/java/de/unistuttgart/overworldbackend/data/PlayerTaskActionLog.java
  src/main/java/de/unistuttgart/overworldbackend/data/PlayerTaskStatistic.java
  src/main/java/de/unistuttgart/overworldbackend/data/config/CourseConfig.java
  src/main/java/de/unistuttgart/overworldbackend/data/mapper/CourseMapper.java
  src/main/java/de/unistuttgart/overworldbackend/data/mapper/LectureMapper.java
  src/main/java/de/unistuttgart/overworldbackend/repositories/AreaBaseRepository.java
  src/main/java/de/unistuttgart/overworldbackend/repositories/CourseRepository.java
  src/main/java/de/unistuttgart/overworldbackend/repositories/DungeonRepository.java
  src/main/java/de/unistuttgart/overworldbackend/repositories/NPCRepository.java
  src/main/java/de/unistuttgart/overworldbackend/repositories/PlayerNPCStatisticRepository.java
  src/main/java/de/unistuttgart/overworldbackend/repositories/PlayerStatisticRepository.java
  src/main/java/de/unistuttgart/overworldbackend/repositories/PlayerTaskStatisticRepository.java
  src/main/java/de/unistuttgart/overworldbackend/repositories/WorldRepository.java
  src/main/java/de/unistuttgart/overworldbackend/service/AreaService.java
  src/main/java/de/unistuttgart/overworldbackend/service/CourseService.java
  src/main/java/de/unistuttgart/overworldbackend/service/DungeonService.java
  src/main/java/de/unistuttgart/overworldbackend/service/MinigameTaskService.java
  src/main/java/de/unistuttgart/overworldbackend/service/NPCService.java
  src/main/java/de/unistuttgart/overworldbackend/service/PlayerNPCStatisticService.java
  src/main/java/de/unistuttgart/overworldbackend/service/PlayerStatisticService.java
  src/main/java/de/unistuttgart/overworldbackend/service/PlayerTaskStatisticService.java
  src/main/java/de/unistuttgart/overworldbackend/service/WorldService.java
  src/test/java/de/unistuttgart/overworldbackend/CourseControllerTest.java
  src/test/java/de/unistuttgart/overworldbackend/DungeonControllerTest.java
  src/test/java/de/unistuttgart/overworldbackend/LectureControllerTest.java
  src/test/java/de/unistuttgart/overworldbackend/MinigameInputControllerTest.java
  src/test/java/de/unistuttgart/overworldbackend/MinigameTaskControllerTest.java
  src/test/java/de/unistuttgart/overworldbackend/NPCControllerTest.java
  src/test/java/de/unistuttgart/overworldbackend/NPCInputControllerTest.java
  src/test/java/de/unistuttgart/overworldbackend/PlayerNPCStatisticControllerTest.java
  src/test/java/de/unistuttgart/overworldbackend/PlayerStatisticControllerTest.java
  src/test/java/de/unistuttgart/overworldbackend/PlayerTaskStatisticControllerTest.java
  src/test/java/de/unistuttgart/overworldbackend/WorldControllerTest.java
Labels: maintenance
