Repository Gamify-IT/overworld-backend, pull requests merged in 2023-04, with the labels that each got.

#68 change the highscore distribution statistic endpoint
  src/main/java/de/unistuttgart/overworldbackend/controller/MinigameTaskStatisticController.java
  src/main/java/de/unistuttgart/overworldbackend/data/PlayerTaskActionLog.java
  src/main/java/de/unistuttgart/overworldbackend/data/statistics/MinigameHighscoreDistribution.java
  src/main/java/de/unistuttgart/overworldbackend/data/statistics/MinigameScoreHit.java
  src/main/java/de/unistuttgart/overworldbackend/service/MinigameTaskStatisticService.java
  src/test/java/de/unistuttgart/overworldbackend/MinigameTaskStatisticTest.java
Labels: maintenance

#59 Refactor course cloning
  .nginx/compose/nginx-complete-dev.conf
  .nginx/compose/nginx-complete.conf
  docker-compose-complete.yaml
  src/main/java/de/unistuttgart/overworldbackend/client/BugfinderClient.java
  src/main/java/de/unistuttgart/overworldbackend/client/ChickenshockClient.java
  src/main/java/de/unistuttgart/overworldbackend/client/CrosswordpuzzleClient.java
  src/main/java/de/unistuttgart/overworldbackend/client/FinitequizClient.java
  src/main/java/de/unistuttgart/overworldbackend/client/TowercrushClient.java
  src/main/java/de/unistuttgart/overworldbackend/data/minigames/bugfinder/BugfinderCode.java
  src/main/java/de/unistuttgart/overworldbackend/data/minigames/bugfinder/BugfinderConfiguration.java
  src/main/java/de/unistuttgart/overworldbackend/data/minigames/bugfinder/BugfinderWord.java
  src/main/java/de/unistuttgart/overworldbackend/data/minigames/chickenshock/ChickenshockConfiguration.java
  src/main/java/de/unistuttgart/overworldbackend/data/minigames/chickenshock/ChickenshockQuestion.java
  src/main/java/de/unistuttgart/overworldbackend/data/minigames/crosswordpuzzle/CrosswordpuzzleConfiguration.java
  src/main/java/de/unistuttgart/overworldbackend/data/minigames/crosswordpuzzle/CrosswordpuzzleQuestion.java
  src/main/java/de/unistuttgart/overworldbackend/data/minigames/finitequiz/FinitequizConfiguration.java
  src/main/java/de/unistuttgart/overworldbackend/data/minigames/finitequiz/FinitequizQuestion.java
  src/main/java/de/unistuttgart/overworldbackend/data/minigames/towercrush/TowercrushConfiguration.java
  src/main/java/de/unistuttgart/overworldbackend/data/minigames/towercrush/TowercrushQuestion.java
  src/main/java/de/unistuttgart/overworldbackend/service/AchievementStatisticService.java
  src/main/java/de/unistuttgart/overworldbackend/service/CourseService.java
  src/main/java/de/unistuttgart/overworldbackend/service/MinigameTaskStatisticService.java
  src/test/java/de/unistuttgart/overworldbackend/CloneTest.java
  src/test/java/de/unistuttgart/overworldbackend/CloneWithoutBackendsTest.java
  src/test/resources/docker-compose-test.yaml
Labels: feature

#69 Refactor unlocking logic
  src/main/java/de/unistuttgart/overworldbackend/client/ChickenshockClient.java
  src/main/java/de/unistuttgart/overworldbackend/data/comparator/AreaComparator.java
  src/main/java/de/unistuttgart/overworldbackend/data/mapper/PlayerStatisticMapper.java
  src/main/java/de/unistuttgart/overworldbackend/repositories/PlayerStatisticRepository.java
  src/main/java/de/unistuttgart/overworldbackend/service/MinigameTaskService.java
  src/main/java/de/unistuttgart/overworldbackend/service/PlayerStatisticService.java
  src/test/java/de/unistuttgart/overworldbackend/AchievementStatisticTest.java
  src/test/java/de/unistuttgart/overworldbackend/CloneWithoutBackendsTest.java
  src/test/java/de/unistuttgart/overworldbackend/KeybindingTest.java
  src/test/java/de/unistuttgart/overworldbackend/UnlockingLogicTest.java
  src/test/resources/docker-compose-test.yaml
Labels: bug

#67 Add unique constraints to `PlayerNPCStatistic` and `PlayerTaskStatistic`
  src/main/java/de/unistuttgart/overworldbackend/data/PlayerNPCStatistic.java
  src/main/java/de/unistuttgart/overworldbackend/data/PlayerTaskStatistic.java
Labels: bug
